server:
  port: 8081
spring:
#  datasource:
#    url: jdbc:mysql://sprint_database:3306/sprint_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: root
#    password: 1234
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      default_batch_fetch_size: 1000


logging:
  level:
    org.hibernate.SQL: debug